// Builds the browser daemon that runs inside cloud sandboxes: the shared
// BrowserController plus a tiny localhost HTTP server, as one .ts file that
// Node runs directly with type stripping. Output is committed.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const controller = readFileSync(join(here, '../src/browser/controller.ts'), 'utf8');
const server = `
// ---- daemon (generated by scripts/gen-daemon.mjs) ----
import { chromium, selectors } from 'playwright';
import http from 'node:http';

const home = process.env.HOME || '/tmp';
await registerSelectors(selectors);
const context = await chromium.launchPersistentContext(home + '/.wren/profile', {
  headless: true,
  viewport: { width: 1280, height: 800 },
  args: ['--no-sandbox', '--disable-dev-shm-usage'],
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0 Safari/537.36 WrenAgent',
});
const controller = new BrowserController(context);
let queue: Promise<unknown> = Promise.resolve();
const server = http.createServer((req, res) => {
  if (req.url === '/health') { res.end('ok'); return; }
  if (req.method !== 'POST' || req.url !== '/act') { res.statusCode = 404; res.end(); return; }
  let body = '';
  req.on('data', (c) => { body += c; });
  req.on('end', () => {
    queue = queue.then(async () => {
      let out;
      try { out = await controller.act(JSON.parse(body)); } catch (e) { out = { ok: false, error: String((e as Error).message) }; }
      res.setHeader('content-type', 'application/json');
      res.end(JSON.stringify(out));
    });
  });
});
server.listen(9333, '127.0.0.1');
`;
const src = controller + server;
writeFileSync(join(here, '../src/browser/daemon-source.ts'), `// Generated by scripts/gen-daemon.mjs - do not edit.\nexport const BROWSER_DAEMON_TS = ${JSON.stringify(src)};\n`);
console.log('wrote daemon-source.ts', src.length, 'chars');
